function [ output ] = AlignCameraImages( config , cam0, cam1 )
    % Align Camera Images - Crop the different camera images to align them
    % Uses the coordinates generated by the CameraCorrelation function to
    % neatly allign two images.

    rowCorrection = config.cameraCorrelation(1);
    colCorrection = config.cameraCorrelation(2); 
        
    splitImage = SplitImage( cam0, 1);
    cam0Crop = splitImage.rightImage;
    cam1Crop = zeros( size(cam0Crop));
    
    rowSize = size( cam0Crop, 1);
    colSize = size( cam0Crop, 2);
    
    for i = 1:colSize
        for j = 1:rowSize
            if (j+rowCorrection > 0 && j+rowCorrection<=rowSize)
               cam1Crop(j,i) = cam1( j+rowCorrection, i+colCorrection);
            end
        end
    end
    
    output.cam0 = cam0Crop;
    output.cam1 = cam1Crop;
    
    figure;
    subplot(1,2,1); imshow( cam0Crop, []); colorbar; title('Cam 0 Aligned')
    subplot(1,2,2); imshow( cam1Crop, []); colorbar; title('Cam 1 Aligned')
end

